---
- name: This ansible-playbook is used to install docker and apache2 web-server onto my ansible-slave-node
  hosts: myhosts
  become: yes
  
  tasks:

    - name: solve the dpkg error
      shell: dpkg --configure -a
      #args:
        #warn: false

    - name: update the system
      apt:
        update_cache: yes
        upgrade: dist

    - name: uninstall any existing versions of docker
      apt:
        name:
          - docker
          - docker.io
          - containerd
          - runc
          - docker-engine
        state: absent
        purge: yes

    - name: create docker apt repository
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
 
    - name: install Docker's official GPG key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        executable: /bin/bash
      
    - name: Add the repository to Apt sources
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | \
        sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash
    
    - name: update after addition of apt sources
      apt:
        update_cache: yes 
    
    - name: install docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: ensure docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: install apache2 web server
      apt:
        name: apache2
        state: present

    - name: start running the apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
